import json
import shutil
import uuid
from contextlib import contextmanager
from hashlib import sha256
from pathlib import Path
from typing import Dict, List, Optional

from fastapi import APIRouter, Body, Depends, HTTPException, Query, Request
from pydantic import BaseModel
from slowapi import Limiter
from slowapi.util import get_remote_address
from starlette.responses import PlainTextResponse

from app.models.auth import Auth
from app.utils.auth_utils import verify_token, FILE_PATH_USER, UserField
from app.utils.conf_utils import get_share_code_path, get_share_data_path, get_user_data_path
from app.utils.json_store import edit_json, write_json
from app.utils.time_utils import get_utc_timestamp
from app.utils.usage_utils import get_user_max_mb, get_user_usage_bytes
from app import messages

router = APIRouter()
limiter = Limiter(key_func=get_remote_address)

FILE_PATH_SHARE = "share.json"
FILE_PATH_USER_SHARES = "shares.json"
SHARE_FILES_DIR = "files"

ROLE_OWNER = "owner"
ROLE_WRITE = "write"
ROLE_READ = "read"

SHARE_CODE_TTL_SECONDS = 24 * 60 * 60


class ShareCreateRequest(BaseModel):
    name: Optional[str] = None  # opaque to the server, client may encrypt it
    encrypted_key: str  # share key wrapped with the owner's own public key


class ShareMemberRequest(BaseModel):
    code: str  # one-time share code generated by the member
    encrypted_key: str  # share key wrapped with the member's public key
    # Fingerprint of the public key the owner actually wrapped the share key
    # with. The owner obtains this fingerprint from the invitee out-of-band
    # (over the same trusted channel as the code) and the server binds the
    # redemption to the key pinned when the code was created. This prevents the
    # server from substituting its own public key to intercept the share key.
    public_key_fingerprint: str
    role: str = ROLE_WRITE


class ShareKeysRequest(BaseModel):
    keys: Dict[str, str]  # username -> share key wrapped with that member's public key


class FileItem(BaseModel):
    name: str
    data: str


class FilesDeleteRequest(BaseModel):
    files: List[str]


def _fingerprint(public_key: str) -> str:
    """Stable fingerprint of a public key, used to verify key authenticity
    out-of-band. Both the invitee and the owner hash the same key string, so a
    server that substitutes a different key produces a mismatching fingerprint."""
    return sha256((public_key or "").encode("utf-8")).hexdigest()


def _share_file(share_id: str, app: str) -> Path:
    try:
        uuid.UUID(share_id)
    except ValueError:
        raise HTTPException(status_code=400, detail=messages.invalidPath)
    share_file = get_share_data_path(share_id, app) / FILE_PATH_SHARE
    if not share_file.exists():
        raise HTTPException(status_code=404, detail=messages.shareNotFound)
    return share_file


def _load_share(share_id: str, app: str):
    share_file = _share_file(share_id, app)
    with open(share_file) as f:
        return share_file.parent, json.load(f)


@contextmanager
def _edit_share(share_id: str, app: str):
    """Locked read-modify-write on a share's metadata. Mutations to the
    yielded dict are persisted atomically on clean exit."""
    share_file = _share_file(share_id, app)
    with edit_json(share_file) as ref:
        yield ref.data


def _save_share(share_path: Path, share: dict):
    write_json(share_path / FILE_PATH_SHARE, share)


def _require_member(share: dict, username: str, write: bool = False) -> dict:
    member = share.get("members", {}).get(username)
    if member is None:
        raise HTTPException(status_code=403, detail=messages.notShareMember)
    if write and member.get("role") == ROLE_READ:
        raise HTTPException(status_code=403, detail=messages.readOnlyShareMember)
    return member


def _require_owner(share: dict, username: str):
    if share.get("owner") != username:
        raise HTTPException(status_code=403, detail=messages.notShareOwner)


def _resolve_share_code(code: str, app: str):
    try:
        uuid.UUID(code)
    except ValueError:
        raise HTTPException(status_code=400, detail=messages.invalidPath)
    code_file = get_share_code_path(code, app)
    if not code_file.exists():
        raise HTTPException(status_code=404, detail=messages.shareCodeNotFound)
    with open(code_file) as f:
        code_data = json.load(f)
    if get_utc_timestamp() > code_data.get("created_at", 0) + SHARE_CODE_TTL_SECONDS:
        code_file.unlink(missing_ok=True)
        raise HTTPException(status_code=410, detail=messages.shareCodeExpired)
    return code_file, code_data


def _update_user_share_index(username: str, app: str, share_id: str, add: bool):
    user_path = get_user_data_path(username, app)
    if not user_path.exists():
        return
    index_file = user_path / FILE_PATH_USER_SHARES
    with edit_json(index_file, default=[]) as ref:
        share_ids = ref.data
        if add and share_id not in share_ids:
            share_ids.append(share_id)
        if not add and share_id in share_ids:
            share_ids.remove(share_id)


def _member_view(share: dict, username: str) -> dict:
    """Share as seen by one member: their own wrapped key, other members without keys."""
    return {
        "id": share["id"],
        "name": share.get("name"),
        "owner": share["owner"],
        "created_at": share.get("created_at"),
        "role": share["members"][username].get("role"),
        "encrypted_key": share["members"][username].get("encrypted_key"),
        "members": [
            {
                "username": u,
                "role": m.get("role"),
                "added_at": m.get("added_at"),
                "public_key_fingerprint": m.get("public_key_fingerprint"),
            }
            for u, m in share.get("members", {}).items()
        ],
    }


def _check_share_storage_limit(share_path: Path, share: dict, app: str, incoming_bytes: int):
    """Shared space storage counts against the share owner's quota."""
    owner_path = get_user_data_path(share.get("owner"), app)
    max_mb = get_user_max_mb(owner_path, app)
    if max_mb is None:
        return
    if get_user_usage_bytes(share_path) + incoming_bytes > max_mb * 1024 * 1024:
        raise HTTPException(status_code=413, detail=messages.storageLimitExceeded)


def _resolve_share_file_path(share_path: Path, *parts: str) -> Path:
    files_base = (share_path / SHARE_FILES_DIR).resolve()
    target = files_base.joinpath(*parts).resolve()
    if not str(target).startswith(str(files_base) + "/"):
        raise HTTPException(status_code=400, detail=messages.invalidPath)
    return target


@router.post("/share", tags=["share"])
@limiter.limit("30/minute")
def create_share(request: Request, req: ShareCreateRequest, auth: Auth = Depends(verify_token)):
    """
    Create a new end-to-end encrypted shared space.

    **Authentication Required**: Yes (via headers)

    **Request Body** (JSON):
    ```json
    {
        "name": "family-vault",
        "encrypted_key": "share_key_wrapped_with_own_public_key"
    }
    ```

    **Client-side flow**:
    1. Generate a random symmetric share key
    2. Encrypt (wrap) it with your own public key
    3. Send only the wrapped key - the server never sees the plaintext key

    **Response**:
    ```json
    {
        "share": { "id": "...", "owner": "...", "role": "owner", ... }
    }
    ```
    """
    share_id = str(uuid.uuid4())
    share_path = get_share_data_path(share_id, auth.app)
    share_path.mkdir(parents=True)
    share = {
        "id": share_id,
        "name": req.name,
        "owner": auth.username,
        "created_at": get_utc_timestamp(),
        "members": {
            auth.username: {
                "role": ROLE_OWNER,
                "encrypted_key": req.encrypted_key,
                "added_at": get_utc_timestamp(),
            }
        },
    }
    _save_share(share_path, share)
    _update_user_share_index(auth.username, auth.app, share_id, add=True)
    return {"share": _member_view(share, auth.username)}


@router.get("/shares", tags=["share"])
@limiter.limit("60/minute")
def list_shares(request: Request, auth: Auth = Depends(verify_token)):
    """
    List all shared spaces the authenticated user owns or is a member of.

    Each entry includes the caller's own wrapped share key (`encrypted_key`),
    which the client decrypts locally with its private key.
    """
    user_path = get_user_data_path(auth.username, auth.app)
    index_file = user_path / FILE_PATH_USER_SHARES
    share_ids = []
    if index_file.exists():
        with open(index_file) as f:
            share_ids = json.load(f)

    shares = []
    for share_id in share_ids:
        share_file = get_share_data_path(share_id, auth.app) / FILE_PATH_SHARE
        if not share_file.exists():
            continue
        with open(share_file) as f:
            share = json.load(f)
        if auth.username in share.get("members", {}):
            shares.append(_member_view(share, auth.username))
    return {"shares": shares}


@router.get("/share/{share_id}", tags=["share"])
@limiter.limit("60/minute")
def get_share(request: Request, share_id: str, auth: Auth = Depends(verify_token)):
    """
    Get one shared space: metadata, member list, and the caller's wrapped share key.
    """
    share_path, share = _load_share(share_id, auth.app)
    _require_member(share, auth.username)
    return {"share": _member_view(share, auth.username)}


@router.delete("/share/{share_id}", tags=["share"])
@limiter.limit("30/minute")
def delete_share(request: Request, share_id: str, auth: Auth = Depends(verify_token)):
    """
    Permanently delete a shared space and all its files. Owner only.
    """
    share_path, share = _load_share(share_id, auth.app)
    _require_owner(share, auth.username)

    for username in share.get("members", {}):
        _update_user_share_index(username, auth.app, share_id, add=False)

    shutil.rmtree(share_path)
    return {"message": messages.shareDeleted}


@router.post("/share-code", tags=["share"])
@limiter.limit("10/minute")
def create_share_code(request: Request, auth: Auth = Depends(verify_token)):
    """
    Generate a one-time share code for the authenticated user.

    The user sends this code to a share owner out-of-band. The owner redeems
    it via `POST /share/{share_id}/member` to add the user to a share, which
    consumes the code. Codes expire after 24 hours.

    The response includes a `fingerprint` of the caller's public key, pinned
    into the code at creation time. The invitee must send this fingerprint to
    the owner over the same trusted out-of-band channel as the code. The owner
    verifies it against the key it wraps the share key with, so the server
    cannot substitute its own key to intercept the share key. Clients should
    recompute the fingerprint locally (`SHA256` of the public key string)
    rather than trusting the value the server returns here.

    **Authentication Required**: Yes (via headers)

    **Response**:
    ```json
    {
        "code": "one-time-share-code",
        "fingerprint": "sha256-hex-of-public-key",
        "expires_at": 1789000000
    }
    ```
    """
    code = str(uuid.uuid4())
    code_file = get_share_code_path(code, auth.app)
    code_file.parent.mkdir(parents=True, exist_ok=True)
    created_at = get_utc_timestamp()

    user_file = get_user_data_path(auth.username, auth.app) / FILE_PATH_USER
    with open(user_file) as f:
        public_key = json.load(f).get(UserField.PUBLIC_KEY)
    fingerprint = _fingerprint(public_key)

    write_json(code_file, {
        "username": auth.username,
        "created_at": created_at,
        "public_key": public_key,
        "fingerprint": fingerprint,
    })
    return {"code": code, "fingerprint": fingerprint, "expires_at": created_at + SHARE_CODE_TTL_SECONDS}


@router.get("/share-code/{code}", tags=["share"])
@limiter.limit("30/minute")
def resolve_share_code(request: Request, code: str, auth: Auth = Depends(verify_token)):
    """
    Resolve a share code to the user who generated it, with their public key.

    The share owner calls this to wrap the share key for the code's user
    before redeeming the code via `POST /share/{share_id}/member`. Resolving
    does not consume the code - only redeeming it does.

    The `public_key` and `fingerprint` are the values pinned when the invitee
    created the code, not a live (swappable) copy from the user's profile. The
    owner MUST compare this `fingerprint` against the one received from the
    invitee out-of-band before wrapping the share key; a mismatch means the key
    is not authentic and the owner must abort.

    **Response**:
    ```json
    {
        "username": "bob",
        "public_key": "user_public_key_string",
        "fingerprint": "sha256-hex-of-public-key"
    }
    ```
    """
    code_file, code_data = _resolve_share_code(code, auth.app)
    return {
        "username": code_data.get("username"),
        "public_key": code_data.get("public_key"),
        "fingerprint": code_data.get("fingerprint"),
    }


@router.post("/share/{share_id}/member", tags=["share"])
@limiter.limit("30/minute")
def add_member(request: Request, share_id: str, req: ShareMemberRequest, auth: Auth = Depends(verify_token)):
    """
    Add a member to a shared space by redeeming their one-time share code.
    Owner only. Consumes the code.

    **Request Body** (JSON):
    ```json
    {
        "code": "one-time-share-code-from-the-member",
        "encrypted_key": "share_key_wrapped_with_members_public_key",
        "public_key_fingerprint": "sha256-hex-of-the-key-you-wrapped-for",
        "role": "write"
    }
    ```

    **Client-side flow**:
    1. Receive a share code AND the key fingerprint from the user, out-of-band
    2. Resolve the code to their public key via `GET /share-code/{code}`
    3. Verify the resolved key's fingerprint equals the one received in step 1;
       abort on mismatch (the server may be substituting a key)
    4. Encrypt (wrap) the share key with the verified public key
    5. Send the code, the wrapped key, and the verified fingerprint - the code
       is consumed on success

    The server rejects the request unless `public_key_fingerprint` matches the
    key pinned when the code was created, binding the wrapped key to a specific,
    out-of-band-verified public key.

    **Roles**: `write` (read and modify files) or `read` (read-only).
    """
    if req.role not in (ROLE_WRITE, ROLE_READ):
        raise HTTPException(status_code=422, detail=messages.somethingWentWrong)

    with _edit_share(share_id, auth.app) as share:
        _require_owner(share, auth.username)

        code_file, code_data = _resolve_share_code(req.code, auth.app)
        username = code_data.get("username")
        pinned_fingerprint = code_data.get("fingerprint")

        if not pinned_fingerprint or req.public_key_fingerprint != pinned_fingerprint:
            raise HTTPException(status_code=400, detail=messages.publicKeyMismatch)

        if username in share.get("members", {}):
            raise HTTPException(status_code=400, detail=messages.alreadyShareMember)

        member_file = get_user_data_path(username, auth.app) / FILE_PATH_USER
        if not member_file.exists():
            raise HTTPException(status_code=404, detail=messages.userNotFound)

        share["members"][username] = {
            "role": req.role,
            "encrypted_key": req.encrypted_key,
            "public_key_fingerprint": pinned_fingerprint,
            "added_at": get_utc_timestamp(),
        }
    _update_user_share_index(username, auth.app, share_id, add=True)
    code_file.unlink(missing_ok=True)
    return {"message": messages.memberAdded, "username": username}


@router.delete("/share/{share_id}/member/{username}", tags=["share"])
@limiter.limit("30/minute")
def remove_member(request: Request, share_id: str, username: str, auth: Auth = Depends(verify_token)):
    """
    Remove a member from a shared space.

    The owner can remove any member; a member can remove themselves (leave).
    The owner cannot be removed - delete the share instead.

    **Security note**: a removed member has had access to the share key.
    After removal the owner's client should rotate: generate a new share key,
    re-encrypt the share's files, and upload re-wrapped keys via
    `PUT /share/{share_id}/keys`.
    """
    with _edit_share(share_id, auth.app) as share:
        if auth.username != username:
            _require_owner(share, auth.username)

        if username == share.get("owner"):
            raise HTTPException(status_code=400, detail=messages.notShareMember)
        if username not in share.get("members", {}):
            raise HTTPException(status_code=404, detail=messages.memberNotFound)

        del share["members"][username]
    _update_user_share_index(username, auth.app, share_id, add=False)
    return {"message": messages.memberRemoved}


@router.put("/share/{share_id}/keys", tags=["share"])
@limiter.limit("30/minute")
def rotate_share_keys(request: Request, share_id: str, req: ShareKeysRequest, auth: Auth = Depends(verify_token)):
    """
    Replace the wrapped share key for every member (key rotation). Owner only.

    Used after removing a member: the owner's client generates a new share
    key, re-encrypts the share's files with it, wraps the new key with each
    remaining member's public key, and uploads all wrapped keys here.

    **Request Body** (JSON):
    ```json
    {
        "keys": {
            "alice": "new_key_wrapped_with_alices_public_key",
            "bob": "new_key_wrapped_with_bobs_public_key"
        }
    }
    ```

    The `keys` map must contain exactly the current members of the share.
    """
    with _edit_share(share_id, auth.app) as share:
        _require_owner(share, auth.username)

        members = share.get("members", {})
        if set(req.keys.keys()) != set(members.keys()):
            raise HTTPException(status_code=400, detail=messages.missingMemberKeys)

        for username, encrypted_key in req.keys.items():
            members[username]["encrypted_key"] = encrypted_key
        share["key_rotated_at"] = get_utc_timestamp()
    return {"message": messages.shareKeysUpdated}


@router.post("/share/{share_id}/file/{folder}/{filename}", tags=["share"])
@limiter.limit("120/minute")
def save_share_file(
        request: Request,
        share_id: str,
        folder: str,
        filename: str,
        data: str = Body(..., media_type="text/plain"),
        auth: Auth = Depends(verify_token)
):
    """
    Save or overwrite a file in a shared space (content encrypted client-side
    with the share key). Requires write access. Counts against the owner's
    storage quota.
    """
    share_path, share = _load_share(share_id, auth.app)
    _require_member(share, auth.username, write=True)

    file_location = _resolve_share_file_path(share_path, folder, filename)
    _check_share_storage_limit(share_path, share, auth.app, len(data.encode("utf-8")))

    file_location.parent.mkdir(parents=True, exist_ok=True)
    with open(file_location, "w", encoding="utf-8") as f:
        f.write(data)
    return {"message": messages.fileSaved}


@router.get("/share/{share_id}/file/{folder}/{filename}", tags=["share"])
@limiter.limit("120/minute")
def get_share_file(
        request: Request,
        share_id: str,
        folder: str,
        filename: str,
        auth: Auth = Depends(verify_token)
):
    """
    Retrieve one file from a shared space as plain text (an encrypted blob
    the client decrypts with the share key). Any member can read.
    """
    share_path, share = _load_share(share_id, auth.app)
    _require_member(share, auth.username)

    file_path = _resolve_share_file_path(share_path, folder, filename)
    if not file_path.exists():
        raise HTTPException(status_code=404, detail=messages.fileNotFound)
    with open(file_path, "r", encoding="utf-8") as f:
        return PlainTextResponse(f.read())


@router.delete("/share/{share_id}/file/{folder}/{filename}", tags=["share"])
@limiter.limit("60/minute")
def delete_share_file(
        request: Request,
        share_id: str,
        folder: str,
        filename: str,
        auth: Auth = Depends(verify_token)
):
    """
    Delete one file from a shared space. Requires write access.
    """
    share_path, share = _load_share(share_id, auth.app)
    _require_member(share, auth.username, write=True)

    file_path = _resolve_share_file_path(share_path, folder, filename)
    if not file_path.exists():
        raise HTTPException(status_code=404, detail=messages.fileNotFound)
    file_path.unlink()
    return {"message": messages.fileDeleted}


@router.get("/share/{share_id}/files/{folder:path}/index", tags=["share"])
@limiter.limit("60/minute")
def get_share_files_index(
        request: Request,
        share_id: str,
        folder: str,
        auth: Auth = Depends(verify_token)
):
    """
    List file names and modification times in a shared-space folder,
    without content. Any member can read.
    """
    share_path, share = _load_share(share_id, auth.app)
    _require_member(share, auth.username)

    folder_path = _resolve_share_file_path(share_path, folder)
    if not folder_path.exists() or not folder_path.is_dir():
        return {"files": []}

    files = [
        {"name": f.name, "time": int(f.stat().st_mtime)}
        for f in folder_path.iterdir() if f.is_file()
    ]
    files.sort(key=lambda f: f["time"], reverse=True)
    return {"files": files}


@router.get("/share/{share_id}/files/{folder:path}", tags=["share"])
@limiter.limit("60/minute")
def get_share_files(
        request: Request,
        share_id: str,
        folder: str,
        start: int = Query(0, ge=0),
        limit: int = Query(100, ge=1, le=1000),
        reverse: bool = Query(False),
        newer_than: Optional[int] = Query(None),
        auth: Auth = Depends(verify_token)
):
    """
    Paginated list of files with content from a shared-space folder.
    Same shape and parameters as `GET /files/{folder}`. Any member can read.
    """
    share_path, share = _load_share(share_id, auth.app)
    _require_member(share, auth.username)

    folder_path = _resolve_share_file_path(share_path, folder)
    if not folder_path.exists() or not folder_path.is_dir():
        return {"files": [], "total": 0, "start": start, "limit": limit, "has_more": False}

    all_files = [f for f in folder_path.iterdir() if f.is_file()]
    if newer_than is not None:
        all_files = [f for f in all_files if f.stat().st_mtime > newer_than]
    all_files_sorted = sorted(all_files, key=lambda f: f.stat().st_mtime, reverse=not reverse)
    total = len(all_files_sorted)

    end = start + limit
    files_with_content = []
    for file_path in all_files_sorted[start:end]:
        try:
            stat = file_path.stat()
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()
            files_with_content.append({
                "name": file_path.name,
                "data": content,
                "time": int(stat.st_mtime)
            })
        except Exception as read_error:
            files_with_content.append({
                "name": file_path.name,
                "data": None,
                "error": f"Failed to read file: {str(read_error)}"
            })

    return {
        "files": files_with_content,
        "total": total,
        "start": start,
        "limit": limit,
        "has_more": end < total
    }


@router.post("/share/{share_id}/files/{folder:path}", tags=["share"])
@limiter.limit("30/minute")
def post_share_files(
        request: Request,
        share_id: str,
        folder: str,
        files: List[FileItem],
        auth: Auth = Depends(verify_token)
):
    """
    Save multiple files into a shared-space folder. Requires write access.
    Same shape as `POST /files/{folder}`.
    """
    share_path, share = _load_share(share_id, auth.app)
    _require_member(share, auth.username, write=True)

    folder_path = _resolve_share_file_path(share_path, folder)

    incoming_bytes = sum(len(f.data.encode("utf-8")) for f in files)
    _check_share_storage_limit(share_path, share, auth.app, incoming_bytes)

    folder_path.mkdir(parents=True, exist_ok=True)

    saved = []
    errors = []
    for file in files:
        if "/" in file.name or "\\" in file.name:
            errors.append({"name": file.name, "error": messages.invalidPath})
            continue
        try:
            (folder_path / file.name).write_text(file.data, encoding="utf-8")
            saved.append(file.name)
        except Exception as e:
            errors.append({"name": file.name, "error": str(e)})

    return {"saved": saved, "errors": errors}


@router.delete("/share/{share_id}/files/{folder:path}", tags=["share"])
@limiter.limit("30/minute")
def delete_share_files(
        request: Request,
        share_id: str,
        folder: str,
        req: FilesDeleteRequest,
        auth: Auth = Depends(verify_token)
):
    """
    Delete multiple files from a shared-space folder. Requires write access.
    Same shape as `DELETE /files/{folder}`.
    """
    share_path, share = _load_share(share_id, auth.app)
    _require_member(share, auth.username, write=True)

    folder_path = _resolve_share_file_path(share_path, folder)

    deleted = []
    errors = []
    for name in req.files:
        if "/" in name or "\\" in name:
            errors.append({"name": name, "error": messages.invalidPath})
            continue
        file_path = folder_path / name
        if not file_path.exists():
            deleted.append(name)
            continue
        try:
            file_path.write_bytes(b"")
            deleted.append(name)
        except Exception as e:
            errors.append({"name": name, "error": str(e)})

    return {"deleted": deleted, "errors": errors}
